### ISSUE TITLE
Segmentation fault ！！

### ISSUE THREAD

**Issue by ami66** [zhangjinsong3/DBNet.tensorRT#1]
python  infer_on_trt_dynamic.py

![56](https://user-images.githubusercontent.com/24771833/106575855-7e55d500-6577-11eb-9a0e-7e8d8701f07a.png)

**Comment by zhangjinsong3** [comment]
Make sure u have compiled the onnx-tensorrt with branch `6.0-full-dims`
[https://github.com/onnx/onnx-tensorrt/tree/6.0-full-dims](url)
