### ISSUE TITLE
acceleration effect

### ISSUE THREAD

**Issue by hua1024** [zhangjinsong3/DBNet.tensorRT#2]
when I transform model to trt , has not acceleration effect
Could you please provide the effect of acceleration comparison

**Comment by zhangjinsong3** [comment]
@hua1024 I test Average inference time by infer_on_trt_dynamic.py with runtime='trt' and 'torch'. Got 
`18.8ms vs 19.6ms` on GTX 1080Ti device.
If U use an Nvidia tesla device run with mode FP16 or INT8, the accelerate ratio maybe better! We deploy the model on Nvidia Tesla T4 with inference time 7ms per image(FP16 mode).

**Comment by hua1024** [comment]
@zhangjinsong3 thanks
