### ISSUE TITLE
onnx dynamic

### ISSUE THREAD

**Issue by gentlebreeze1** [zhangjinsong3/DBNet.tensorRT#3]
请问你的onnx dynamic进行simplifier没有，我的onnx dynamic经过simplifier然后转tensorrt 好像只能处理onnx simplifier中输入的input_shape，并且输出结果也不对。simplify后的模型出现了1*64*0*0这种
![image](https://user-images.githubusercontent.com/27668596/112960879-da218200-9112-11eb-8a33-7843bc815d05.png)
@zhangjinsong3

**Comment by zhangjinsong3** [comment]
@gentlebreeze1 我没有使用onnx-simplifier, 你的onnx-tensorrt有没有编译,编译的是不是full-dims分支

**Comment by gentlebreeze1** [comment]
> @gentlebreeze1 我没有使用onnx-simplifier, 你的onnx-tensorrt有没有编译,编译的是不是full-dims分支
我没有使用onnx-tensorrt直接使用的tensorrt lib配合build_engine函数生成的engine，我最大的输入设置的1*3*1280*1280，dbnet的输出应该是1*2*1280*1280但是得到的是1*3*1280*1280下边是运行时候的截图
![image](https://user-images.githubusercontent.com/27668596/113086806-65048a00-91b0-11eb-921d-a10bdead4f6b.png)

@zhangjinsong3

**Comment by zhangjinsong3** [comment]
@gentlebreeze1 如果你使用 dynamic 推理,一定要编译onnx-tensorrt 6.0-full-dims分支,他们使用不同的接口解析onnx model
