### ISSUE TITLE
请问一下dbnet，tensorrt推理与pth模型直接推理预测 速度大概提升多少呢？ 精度有损吗？ 我自己跑tensorrt推理，速度反而变慢了，求解

### ISSUE THREAD

**Issue by longnanxi** [zhangjinsong3/DBNet.tensorRT#4]

**Comment by zhangjinsong3** [comment]
不太记得了，你是否有使用FP16模式运行tensorRT，一般来说FP16不会掉精度，速度会有30-40%的提升

**Comment by longnanxi** [comment]
FP16确实是比FP32有近40%的速度提升， 可tensorrt 的FP16的推理速度 仍差于pth模型推理的速度

**Comment by zhangjinsong3** [comment]
应该不会吧，我们生产上使用的就是FP16 tensorRT运行，backbone 用的是resnet，tensorRT对resnet系列的加速是很可观的，确保一下torch计时的方式有没有问题
