### ISSUE TITLE
大佬，get_engine这个函数没有定义

### ISSUE THREAD

**Issue by dreamlychina** [zhangjinsong3/DBNet.tensorRT#5]
undefined reference to `BRFD::DBDetector::get_engine(str, str),cpp中只定义了
int DBDetector::get_engine(const std::string onnx_file,
                           const std::string engine_file,
                           IExecutionContext* &context,
                           ICudaEngine* &engine,
                           void* buffers[],
                           std::vector<int64_t >& bufferSize,
                           int inputH,
                           int inputW)
导致  get_engine(model_dir + model_name_1,
             model_dir + filenameWithoutExtension(model_name_1) + ".engine");
找不到函数的定义

**Comment by zhangjinsong3** [comment]
其它几个参数都是成员变量，可以自己传一下，或者修改一下get engine

**Comment by dreamlychina** [comment]
好的，感谢大佬
